# Generated by Django 3.1.6 on 2021-02-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsum_generator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
